/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 as long as the process is alive. Never touches DB.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthLiveResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Checks DB and listener dependencies. Returns 503 when any check fails so load balancers drain this instance without triggering a restart.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready for traffic */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthReadyResponse"];
                    };
                };
                /** @description Not ready — do not route traffic */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthReadyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus scrape endpoint
         * @description Prometheus-format metrics. Requires authentication in production.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus exposition format (text/plain) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
                /** @description Missing or invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Endpoint not configured in current environment */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * USDC fiat prices
         * @description Returns current USDC prices in supported fiat currencies. Public endpoint.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filter to a single fiat code. */
                    fiat?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prices fetched */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PricesResponse"];
                    };
                };
                /** @description Pricing service unavailable */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login
         * @description Exchange admin credentials for a short-lived JWT. Rate-limited to 5 attempts per 15 minutes per IP. Not for regular users — issue JWTs via Dynamic.xyz.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AdminLoginRequest"];
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminLoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all trades (admin)
         * @description Paginated list of every trade. Admin-only.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminTradesResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden (non-admin) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/escrows/{trade_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get escrow by trade id (admin)
         * @description Fetch the escrow row for a given trade. Admin-only.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    trade_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdminEscrowsResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Escrow not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/deadline-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deadline stats across networks
         * @description Aggregate deadline expiry statistics across every network.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeadlineStatsResponse"];
                    };
                };
                /** @description Failed to fetch */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/deadline-stats/{networkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deadline stats for a single network
         * @description Deadline expiry statistics for a specific network.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    networkId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeadlineStatsResponse"];
                    };
                };
                /** @description Network not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create account
         * @description Create an account linked to the authenticated wallet.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAccountRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountMutationResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Account already exists */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my account
         * @description Returns the authenticated wallet's account record.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountFullResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get account by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountGetByIdResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Update account (owner only) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountMutationResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List offers (public)
         * @description List offers filtered by criteria. No auth required.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number | null;
                    owner?: string;
                    token?: string;
                    type?: string;
                };
                header: {
                    /** @description Network identifier (e.g. solana-devnet, celo-alfajores). */
                    "x-network-name": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListOffersResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create offer
         * @description Restricted to the authenticated creator account.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Network identifier (e.g. solana-devnet, celo-alfajores). */
                    "x-network-name": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOfferRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateOfferResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/offers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get offer by id (public) */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Network identifier (e.g. solana-devnet, celo-alfajores). */
                    "x-network-name": string;
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetOfferResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /** Update offer (owner only) */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description Network identifier (e.g. solana-devnet, celo-alfajores). */
                    "x-network-name": string;
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateOfferRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UpdateOfferResponse"];
                    };
                };
                /** @description Not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete offer (owner only) */
        delete: {
            parameters: {
                query?: never;
                header: {
                    /** @description Network identifier (e.g. solana-devnet, celo-alfajores). */
                    "x-network-name": string;
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteOfferResponse"];
                    };
                };
                /** @description Not owner */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create trade
         * @description Create a trade against an existing offer. Accepts Idempotency-Key for retry-safe creation.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description UUID v4. See "Idempotency" in docs/api-ref.md. Recommended on retryable mutations. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTradeRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateTradeResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Idempotency-Key conflict (different body replayed with same key) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my trades
         * @description Returns trades where the authenticated user is a participant.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListMyTradesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trades/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get trade by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetTradeResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Update trade (state transition)
         * @description Transitions the trade state (e.g. MARK_FIAT_PAID). Idempotency-Key recommended — a retry after network failure must not re-mark fiat paid.
         */
        put: {
            parameters: {
                query?: never;
                header: {
                    /** @description UUID v4. See "Idempotency" in docs/api-ref.md. Recommended on retryable mutations. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTradeRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TradeUpdateResponse"];
                    };
                };
                /** @description Invalid state transition */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Idempotency-Key conflict or finalized resource */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record an escrow creation event
         * @description Notifies the API of an escrow created on-chain. `Idempotency-Key` header (UUID v4) is REQUIRED — double-recording an escrow creates ledger drift. See the Idempotency section of docs/api-ref.md for replay semantics.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description UUID v4. See "Idempotency" in docs/api-ref.md. Recommended on retryable mutations. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["EscrowRecordRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EscrowRecordResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Idempotency-Key conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List my escrows */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number | null;
                };
                header: {
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ListMyEscrowsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{onchainEscrowId}/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get on-chain balance for an escrow
         * @description Fetches the current balance directly from the chain via RPC.
         */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path: {
                    onchainEscrowId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EscrowBalanceResponse"];
                    };
                };
                /** @description RPC unavailable (breaker open) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{onchainEscrowId}/stored-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get cached balance from DB */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path: {
                    onchainEscrowId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EscrowStoredBalanceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{onchainEscrowId}/calculated-balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculated balance (stored + adjustments) */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path: {
                    onchainEscrowId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EscrowCalculatedBalanceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{onchainEscrowId}/sequential-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sequential escrow chain info */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path: {
                    onchainEscrowId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EscrowSequentialInfoResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/escrows/{onchainEscrowId}/auto-cancel-eligible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check auto-cancel eligibility */
        get: {
            parameters: {
                query?: never;
                header: {
                    /** @description Target network (e.g. solana-devnet). */
                    "x-network-name": string;
                };
                path: {
                    onchainEscrowId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EscrowAutoCancelResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a blockchain transaction
         * @description Records a confirmed on-chain transaction. `Idempotency-Key` header (UUID v4) is REQUIRED — this is the hottest replay-vulnerable write path and a retry without the key would create a duplicate ledger row. See the Idempotency section of docs/api-ref.md for replay semantics.
         */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description UUID v4. See "Idempotency" in docs/api-ref.md. Recommended on retryable mutations. */
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RecordTransactionRequest"];
                };
            };
            responses: {
                /** @description Recorded */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RecordTransactionResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Idempotency-Key conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/trade/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List transactions for a trade */
        get: {
            parameters: {
                query?: {
                    type?: string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionsByTradeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transactions/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List authenticated user's transactions */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number | null;
                    type?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionsByUserResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Liveness probe response. */
        HealthLiveResponse: {
            /** @enum {string} */
            status: "ok";
            /** Format: date-time */
            timestamp: string;
        };
        /** @description Readiness probe response. 503 when not ready. */
        HealthReadyResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            /** Format: date-time */
            timestamp: string;
            checks: {
                db: {
                    ok: boolean;
                    detail?: string;
                };
                listener: {
                    ok: boolean;
                    detail?: string;
                };
            };
        };
        IdempotencyConflictResponse: {
            /** @enum {string} */
            error: "idempotency_key_conflict";
            message: string;
        };
        /**
         * @description Standard error envelope.
         * @example {
         *       "error": "invalid_value",
         *       "message": "A value failed validation."
         *     }
         */
        ErrorResponse: {
            error: string;
            message?: string;
            details?: string;
        };
        /** @description Page/limit/total pagination metadata. */
        PaginationMeta: {
            page: number;
            limit: number;
            total: number;
        };
        /**
         * @description Current USDC prices in supported fiat currencies.
         * @example {
         *       "status": "success",
         *       "data": {
         *         "USDC": {
         *           "USD": {
         *             "price": "1.00",
         *             "timestamp": 1700000000
         *           }
         *         }
         *       }
         *     }
         */
        PricesResponse: {
            /** @enum {string} */
            status: "success";
            data: {
                USDC: {
                    [key: string]: {
                        price: string;
                        timestamp: number;
                    };
                };
            };
        };
        AdminLoginRequest: {
            username: string;
            password: string;
        };
        AdminLoginResponse: {
            token: string;
            expiresIn: number;
        };
        AdminTradesResponse: {
            data: {
                id: number;
                leg1_offer_id: number | null;
                leg2_offer_id: number | null;
                overall_status: string;
                from_fiat_currency: string;
                destination_fiat_currency: string;
                from_bank: string | null;
                destination_bank: string | null;
                leg1_state: string | null;
                leg2_state: string | null;
                leg1_seller_account_id: number | null;
                leg1_buyer_account_id: number | null;
                leg2_seller_account_id: number | null;
                leg2_buyer_account_id: number | null;
                leg1_crypto_amount: string | null;
                leg2_crypto_amount: string | null;
                leg1_crypto_token: string | null;
                leg2_crypto_token: string | null;
                leg1_fiat_amount: string | null;
                leg2_fiat_amount: string | null;
                completed: boolean | null;
                /** Format: date-time */
                completed_at: string | null;
                cancelled: boolean | null;
                /** Format: date-time */
                cancelled_at: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            meta: components["schemas"]["PaginationMeta"];
        };
        AdminEscrowsResponse: {
            data: {
                id: number;
                trade_id: number | null;
                network_id: number;
                onchain_escrow_id: string | null;
                state: string;
                current_balance: string | null;
                seller_address: string | null;
                buyer_address: string | null;
                arbitrator_address: string | null;
                amount: string | null;
                token_type: string | null;
                /** Format: date-time */
                deposit_deadline: string | null;
                /** Format: date-time */
                fiat_deadline: string | null;
                fiat_paid: boolean | null;
                /** Format: date-time */
                completed_at: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
            }[];
            meta: components["schemas"]["PaginationMeta"];
        };
        DeadlineStatsResponse: {
            success: boolean;
            data?: unknown;
            /** Format: date-time */
            timestamp: string;
        };
        CreateAccountRequest: {
            /** Format: email */
            email: string;
            username: string;
            wallet_address: string;
        };
        UpdateAccountRequest: {
            available_from?: string;
            available_to?: string;
            /** Format: email */
            email?: string;
            phone_country_code?: string;
            phone_number?: string;
            /** Format: uri */
            profile_photo_url?: string;
            telegram_id?: number;
            telegram_username?: string;
            timezone?: string;
            username?: string;
        };
        AccountMutationResponse: {
            id: number;
        };
        AccountFullResponse: {
            available_from: string | null;
            available_to: string | null;
            created_at: string;
            email: string;
            id: number;
            phone_country_code: string | null;
            phone_number: string | null;
            profile_photo_url: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            telegram_id: string | number | null;
            telegram_username: string | null;
            timezone: string | null;
            updated_at: string;
            username: string;
            wallet_address: string;
        };
        AccountGetByIdResponse: {
            available_from: string | null;
            available_to: string | null;
            created_at: string;
            email: string;
            id: number;
            phone_country_code: string | null;
            phone_number: string | null;
            profile_photo_url: string | null;
            /** @enum {string} */
            role: "user" | "admin";
            telegram_id: string | number | null;
            telegram_username: string | null;
            timezone: string | null;
            updated_at: string;
            username: string;
            wallet_address: string;
        } | {
            available_from: string | null;
            available_to: string | null;
            created_at: string;
            id: number;
            profile_photo_url: string | null;
            telegram_id: string | number | null;
            telegram_username: string | null;
            timezone: string | null;
            username: string;
            wallet_address: string;
        };
        ListOffersResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            offers: {
                created_at: string;
                creator_account_id: number;
                escrow_deposit_time_limit: string | null;
                fiat_currency: string;
                fiat_payment_time_limit: string | null;
                id: number;
                max_amount: string;
                min_amount: string;
                network_id: number;
                offer_type: string;
                rate_adjustment: string;
                terms: string | null;
                token: string;
                total_available_amount: string;
                updated_at: string;
            }[];
        };
        GetOfferResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            offer: {
                created_at: string;
                creator_account_id: number;
                escrow_deposit_time_limit: string | null;
                fiat_currency: string;
                fiat_payment_time_limit: string | null;
                id: number;
                max_amount: string;
                min_amount: string;
                network_id: number;
                offer_type: string;
                rate_adjustment: string;
                terms: string | null;
                token: string;
                total_available_amount: string;
                updated_at: string;
            };
        };
        CreateOfferRequest: {
            creator_account_id: number;
            escrow_deposit_time_limit?: string;
            /** @default USD */
            fiat_currency: string;
            fiat_payment_time_limit?: string;
            max_amount?: string;
            min_amount: string;
            /** @enum {string} */
            offer_type: "BUY" | "SELL";
            rate_adjustment?: number;
            terms?: string;
            /** @enum {string} */
            token?: "USDC";
            total_available_amount?: string;
        };
        CreateOfferResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            offer: {
                created_at: string;
                creator_account_id: number;
                escrow_deposit_time_limit: string | null;
                fiat_currency: string;
                fiat_payment_time_limit: string | null;
                id: number;
                max_amount: string;
                min_amount: string;
                network_id: number;
                offer_type: string;
                rate_adjustment: string;
                terms: string | null;
                token: string;
                total_available_amount: string;
                updated_at: string;
            };
        };
        UpdateOfferRequest: {
            escrow_deposit_time_limit?: string | {
                minutes: number;
            };
            fiat_currency?: string;
            fiat_payment_time_limit?: string | {
                minutes: number;
            };
            max_amount?: string;
            min_amount?: string;
            /** @enum {string} */
            offer_type?: "BUY" | "SELL";
            rate_adjustment?: number;
            terms?: string;
            /** @enum {string} */
            token?: "USDC";
            total_available_amount?: string;
        };
        UpdateOfferResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            offer: {
                created_at: string;
                creator_account_id: number;
                escrow_deposit_time_limit: string | null;
                fiat_currency: string;
                fiat_payment_time_limit: string | null;
                id: number;
                max_amount: string;
                min_amount: string;
                network_id: number;
                offer_type: string;
                rate_adjustment: string;
                terms: string | null;
                token: string;
                total_available_amount: string;
                updated_at: string;
            };
        };
        DeleteOfferResponse: {
            /** @enum {string} */
            message: "Offer deleted";
        };
        CreateTradeRequest: {
            destination_bank?: string;
            destination_fiat_currency?: string;
            from_bank?: string;
            from_fiat_currency?: string;
            leg1_crypto_amount?: string;
            leg1_fiat_amount?: string;
            leg1_offer_id: number;
            leg2_offer_id?: number;
        };
        CreateTradeResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            trade: {
                cancelled: boolean;
                cancelled_at?: string | null;
                completed: boolean;
                completed_at?: string | null;
                created_at: string;
                destination_bank: string | null;
                destination_fiat_currency: string;
                from_bank: string | null;
                from_fiat_currency: string;
                id: number;
                leg1_offer_id: number | null;
                leg2_offer_id: number | null;
                network_id: number;
                overall_status: string;
                updated_at: string;
                leg1_buyer_account_id: number | null;
                leg1_cancelled_at?: string | null;
                leg1_cancelled_by?: string | null;
                leg1_created_at: string;
                leg1_crypto_amount: string;
                leg1_crypto_token: string;
                leg1_dispute_id?: number | null;
                leg1_escrow_address?: string | null;
                leg1_escrow_deposit_deadline?: string | null;
                leg1_escrow_onchain_id?: string | null;
                leg1_fiat_amount: string | null;
                leg1_fiat_currency: string;
                leg1_fiat_paid_at?: string | null;
                leg1_fiat_payment_deadline?: string | null;
                leg1_released_at?: string | null;
                leg1_seller_account_id: number | null;
                leg1_state: string;
                leg2_buyer_account_id?: number | null;
                leg2_cancelled_at?: string | null;
                leg2_cancelled_by?: string | null;
                leg2_created_at?: string | null;
                leg2_crypto_amount?: string | null;
                leg2_crypto_token?: string | null;
                leg2_dispute_id?: number | null;
                leg2_escrow_address?: string | null;
                leg2_escrow_deposit_deadline?: string | null;
                leg2_escrow_onchain_id?: string | null;
                leg2_fiat_amount?: string | null;
                leg2_fiat_currency?: string | null;
                leg2_fiat_paid_at?: string | null;
                leg2_fiat_payment_deadline?: string | null;
                leg2_released_at?: string | null;
                leg2_seller_account_id?: number | null;
                leg2_state?: string | null;
            };
        };
        GetTradeResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            trade: {
                cancelled: boolean;
                cancelled_at?: string | null;
                completed: boolean;
                completed_at?: string | null;
                created_at: string;
                destination_bank: string | null;
                destination_fiat_currency: string;
                from_bank: string | null;
                from_fiat_currency: string;
                id: number;
                leg1_offer_id: number | null;
                leg2_offer_id: number | null;
                network_id: number;
                overall_status: string;
                updated_at: string;
                leg1_buyer_account_id: number | null;
                leg1_cancelled_at?: string | null;
                leg1_cancelled_by?: string | null;
                leg1_created_at: string;
                leg1_crypto_amount: string;
                leg1_crypto_token: string;
                leg1_dispute_id?: number | null;
                leg1_escrow_address?: string | null;
                leg1_escrow_deposit_deadline?: string | null;
                leg1_escrow_onchain_id?: string | null;
                leg1_fiat_amount: string | null;
                leg1_fiat_currency: string;
                leg1_fiat_paid_at?: string | null;
                leg1_fiat_payment_deadline?: string | null;
                leg1_released_at?: string | null;
                leg1_seller_account_id: number | null;
                leg1_state: string;
                leg2_buyer_account_id?: number | null;
                leg2_cancelled_at?: string | null;
                leg2_cancelled_by?: string | null;
                leg2_created_at?: string | null;
                leg2_crypto_amount?: string | null;
                leg2_crypto_token?: string | null;
                leg2_dispute_id?: number | null;
                leg2_escrow_address?: string | null;
                leg2_escrow_deposit_deadline?: string | null;
                leg2_escrow_onchain_id?: string | null;
                leg2_fiat_amount?: string | null;
                leg2_fiat_currency?: string | null;
                leg2_fiat_paid_at?: string | null;
                leg2_fiat_payment_deadline?: string | null;
                leg2_released_at?: string | null;
                leg2_seller_account_id?: number | null;
                leg2_state?: string | null;
            };
        };
        ListMyTradesResponse: {
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            trades: {
                cancelled: boolean;
                cancelled_at?: string | null;
                completed: boolean;
                completed_at?: string | null;
                created_at: string;
                destination_bank: string | null;
                destination_fiat_currency: string;
                from_bank: string | null;
                from_fiat_currency: string;
                id: number;
                leg1_offer_id: number | null;
                leg2_offer_id: number | null;
                network_id: number;
                overall_status: string;
                updated_at: string;
                leg1_buyer_account_id: number | null;
                leg1_cancelled_at?: string | null;
                leg1_cancelled_by?: string | null;
                leg1_created_at: string;
                leg1_crypto_amount: string;
                leg1_crypto_token: string;
                leg1_dispute_id?: number | null;
                leg1_escrow_address?: string | null;
                leg1_escrow_deposit_deadline?: string | null;
                leg1_escrow_onchain_id?: string | null;
                leg1_fiat_amount: string | null;
                leg1_fiat_currency: string;
                leg1_fiat_paid_at?: string | null;
                leg1_fiat_payment_deadline?: string | null;
                leg1_released_at?: string | null;
                leg1_seller_account_id: number | null;
                leg1_state: string;
                leg2_buyer_account_id?: number | null;
                leg2_cancelled_at?: string | null;
                leg2_cancelled_by?: string | null;
                leg2_created_at?: string | null;
                leg2_crypto_amount?: string | null;
                leg2_crypto_token?: string | null;
                leg2_dispute_id?: number | null;
                leg2_escrow_address?: string | null;
                leg2_escrow_deposit_deadline?: string | null;
                leg2_escrow_onchain_id?: string | null;
                leg2_fiat_amount?: string | null;
                leg2_fiat_currency?: string | null;
                leg2_fiat_paid_at?: string | null;
                leg2_fiat_payment_deadline?: string | null;
                leg2_released_at?: string | null;
                leg2_seller_account_id?: number | null;
                leg2_state?: string | null;
            }[];
        };
        UpdateTradeRequest: {
            fiat_paid?: boolean;
            /** @enum {string} */
            leg1_state?: "CREATED" | "FUNDED" | "FIAT_PAID" | "RELEASED" | "CANCELLED" | "DISPUTED" | "RESOLVED" | "COMPLETED";
            /** @enum {string} */
            overall_status?: "IN_PROGRESS" | "DISPUTED" | "COMPLETED" | "CANCELLED";
        };
        TradeUpdateResponse: {
            id: number;
        };
        EscrowRecordRequest: {
            transaction_hash?: string;
            signature?: string;
            onchain_escrow_id: string;
            metadata?: unknown;
        };
        EscrowRecordResponse: {
            blockExplorerUrl: string;
            escrowDbId: number;
            escrowId: string;
            /** @enum {string} */
            networkFamily: "evm" | "solana";
            /** @enum {boolean} */
            success: true;
            txHash: string;
        };
        ListMyEscrowsResponse: {
            amount: string;
            arbitrator_address: string;
            buyer_address: string;
            completed_at?: string | null;
            counter: number;
            created_at: string;
            current_balance: string | null;
            deposit_deadline?: string | null;
            dispute_id?: number | null;
            escrow_address: string;
            escrow_onchain_id?: string | null;
            escrow_pda?: string | null;
            escrow_token_account?: string | null;
            fiat_deadline?: string | null;
            fiat_paid: boolean;
            id: number;
            network?: string;
            network_family: string;
            network_id: number;
            onchain_escrow_id?: string | null;
            program_id?: string | null;
            seller_address: string;
            sequential: boolean;
            sequential_escrow_address?: string | null;
            state: string;
            token_type: string;
            trade_id: number;
            trade_onchain_id?: string | null;
            updated_at: string;
            version?: string | null;
        }[];
        EscrowBalanceResponse: {
            balance: string;
            escrowId: string;
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
        };
        EscrowStoredBalanceResponse: {
            escrowId: string;
            storedBalance: string;
        };
        EscrowCalculatedBalanceResponse: {
            calculatedBalance: string;
            escrowId: string;
        };
        EscrowSequentialInfoResponse: {
            escrowId: string;
            /** @enum {string} */
            network: "celo-alfajores" | "celo-mainnet" | "solana-devnet" | "solana-mainnet";
            sequentialInfo?: unknown;
        };
        EscrowAutoCancelResponse: {
            escrowId: string;
            isEligibleForAutoCancel: boolean;
        };
        RecordTransactionRequest: {
            block_number?: number;
            escrow_id?: string | number;
            from_address: string;
            metadata?: {
                [key: string]: string | number | boolean | null;
            } | string;
            signature?: string;
            /**
             * @default PENDING
             * @enum {string}
             */
            status: "PENDING" | "SUCCESS" | "FAILED";
            to_address?: string;
            trade_id: number;
            transaction_hash?: string;
            /** @enum {string} */
            transaction_type: "CREATE_ESCROW" | "FUND_ESCROW" | "RELEASE_ESCROW" | "CANCEL_ESCROW" | "MARK_FIAT_PAID" | "OPEN_DISPUTE" | "RESPOND_DISPUTE" | "RESOLVE_DISPUTE" | "DISPUTE_ESCROW" | "OTHER";
        };
        RecordTransactionResponse: {
            blockNumber: number | null;
            /** @enum {boolean} */
            success: true;
            transactionId: number;
            txHash: string;
        };
        TransactionsByTradeResponse: {
            amount?: string | null;
            created_at: string;
            error_message: string | null;
            escrow_id: number | null;
            from_address: string | null;
            gas_used: string | null;
            id: number | string;
            metadata?: unknown;
            network: string | null;
            to_address: string | null;
            token_type?: string | null;
            trade_id: number | null;
            transaction_hash: string | null;
            transaction_type: string;
            status: string;
        }[];
        TransactionsByUserResponse: {
            amount?: string | null;
            created_at: string;
            error_message: string | null;
            escrow_id: number | null;
            from_address: string | null;
            gas_used: string | null;
            id: number | string;
            metadata?: unknown;
            network: string | null;
            to_address: string | null;
            token_type?: string | null;
            trade_id: number | null;
            transaction_hash: string | null;
            transaction_type: string;
            status: string;
        }[];
        /**
         * Format: uuid
         * @description UUID v4. See "Idempotency" in docs/api-ref.md. Recommended on retryable mutations.
         * @example 9d6b9e4c-3a2f-4f1a-8b8d-2b5a6e0f5b21
         */
        IdempotencyKey: string;
        /**
         * @description Target network identifier (e.g. `solana-devnet`, `celo-alfajores`). Required on chain-aware endpoints.
         * @example solana-devnet
         */
        NetworkName: string;
    };
    responses: never;
    parameters: {
        /** @description UUID v4. See "Idempotency" in docs/api-ref.md. Recommended on retryable mutations. */
        IdempotencyKey: components["schemas"]["IdempotencyKey"];
        /** @description Target network identifier (e.g. `solana-devnet`, `celo-alfajores`). Required on chain-aware endpoints. */
        NetworkName: components["schemas"]["NetworkName"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
